NETWORK=testnet_aurora

deploy:
	yarn hardhat run scripts/deploy.js --network ${NETWORK}
deploy2:
	yarn hardhat run scripts/deploy2.js --network ${NETWORK}

deployNFT:
	yarn hardhat run scripts/deployNFT.js --network ${NETWORK}
